[workspace]
resolver = "3"
members = ["kernel"]

[features]
qemu-test = ["kernel/qemu-test"]

[profile.dev]
panic = "abort"

[package]
name = "wovenhat-os"
version = "0.0.1"
edition = "2024"

[dependencies]
ovmf-prebuilt = "0.2.4"

[build-dependencies]
kernel = { package = "wovenhat-kernel", path = "kernel", artifact = "bin", target = "x86_64-unknown-none" }

bootloader = { version = "0.11.17", default-features = false, features = ["uefi"] }
