[workspace]
resolver = "3"
members = ["kernel"]

[package]
name = "wovenhat-os"
version = "0.0.1"
edition = "2024"

[dependencies]
ovmf-prebuilt = "0.2.4"

[build-dependencies]
kernel = {
    package = "wovenhat-kernel",
    path = "kernel",
    artifact = "bin",
    target = "x86_64-unknown-none"
}

bootloader = "0.11.17"