[package]
name = "wovenhat-kernel"
version = "0.0.1"
edition = "2021"

[features]
qemu-test = []

[dependencies]
bootloader_api = "0.11.17"
x86_64 = "0.15.5"
spin = "0.10"

smoltcp = { version = "0.14", default-features = false, features = [
    "alloc",
    "medium-ethernet",
    "proto-ipv4",
    "socket-icmp",
    "socket-udp",
    "socket-tcp",
] }